#request
string topic
string mode
string quality
float64 rate
bool motion
bool blur
bool similar
string collection
string db_host
string tf_msg_str
string tf_base
string tf_cam

---
#response
bool success