#request
string topic
string format
string iai_id
int32 jpeg_quality
int32 png_level
int32 optimize_for
int32 target_bitrate
int32 keyframe_frequency
int32 quality
float64 depth_max           # is double
float64 depth_quantization  # is double
string db_host
string collection
int32 mode
float64 rate                # is double
bool motion
bool blur
bool similar
---
bool success